language: r
cache: packages

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r_check_args: '--use-valgrind'
    - os: osx
      osx_image: xcode8.3

addons:
  apt:
    packages:
    - valgrind

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi