// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// compressBits
Rcpp::IntegerVector compressBits(const Rcpp::IntegerVector x);
RcppExport SEXP bitjson_compressBits(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(compressBits(x));
    return rcpp_result_gen;
END_RCPP
}
// decompressBits
Rcpp::IntegerVector decompressBits(const Rcpp::IntegerVector y);
RcppExport SEXP bitjson_decompressBits(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(decompressBits(y));
    return rcpp_result_gen;
END_RCPP
}
