# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compressBits <- function(x) {
    .Call('bitjson_compressBits', PACKAGE = 'bitjson', x)
}

decompressBits <- function(y) {
    .Call('bitjson_decompressBits', PACKAGE = 'bitjson', y)
}

